name = "hyprstock"
main = "src/index.js"
compatibility_date = "2024-10-25"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "hyperstock-db"
database_id = "fbee7162-6917-420a-9789-e687d60e4550"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1